In [1]:
!pip -q install requests beautifulsoup4 lxml

In [2]:
import os
import re
import time
from datetime import datetime
from urllib.parse import urljoin

import pandas as pd
import requests
from bs4 import BeautifulSoup

In [3]:
BASE_URL = "https://chelyabinsk.cian.ru/kupit-kvartiru/"

RAW_BASE_DIR = "data/2026/raw_cian"
PROCESSED_BASE_DIR = "data/2026/processed_cian"
DEBUG_BASE_DIR = "data/2026/debug_cian"

os.makedirs(RAW_BASE_DIR, exist_ok=True)
os.makedirs(PROCESSED_BASE_DIR, exist_ok=True)
os.makedirs(DEBUG_BASE_DIR, exist_ok=True)

In [4]:
session = requests.Session()
session.headers.update({
    "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36",
    "Accept-Language": "ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7",
    "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
})

In [5]:
def clean_text(value):
    if value is None:
        return None
    value = re.sub(r"\s+", " ", str(value)).strip()
    return value or None

def to_float(value):
    if value is None:
        return None
    s = str(value).replace("\xa0", " ").replace(",", ".")
    s = re.sub(r"[^0-9.]", "", s)
    if not s:
        return None
    try:
        return float(s)
    except:
        return None

def to_int(value):
    if value is None:
        return None
    s = re.sub(r"[^0-9]", "", str(value))
    if not s:
        return None
    try:
        return int(s)
    except:
        return None

def parse_price(text):
    if not text:
        return None
    m = re.search(r"([\d\s\xa0]+)\s*₽", str(text))
    if m:
        return to_float(m.group(1))
    return None

def parse_area(text):
    if not text:
        return None
    m = re.search(r"(\d+(?:[.,]\d+)?)\s*м²", str(text).lower())
    if m:
        return to_float(m.group(1))
    return None

def parse_rooms(text):
    if not text:
        return None
    text = str(text).lower()

    if "студия" in text:
        return 0

    for pattern in [
        r"(\d+)\s*-\s*комн",
        r"(\d+)\s*комн",
        r"(\d+)\s*комнат"
    ]:
        m = re.search(pattern, text)
        if m:
            return to_int(m.group(1))

    return None

def parse_floor(text):
    if not text:
        return None

    text = str(text).lower()

    m = re.search(r"(\d+)\s*/\s*(\d+)\s*этаж", text)
    if m:
        return to_int(m.group(1))

    m = re.search(r"(\d+)\s*/\s*(\d+)", text)
    if m:
        return to_int(m.group(1))

    return None

def detect_housing_type(text):
    text = (text or "").lower()

    if any(x in text for x in ["новостройка", "жк ", "сдача корпуса", "первичная продажа", "дом сдан"]):
        return "Новостройка"

    if any(x in text for x in ["нежил", "офис", "коммерческ", "помещение"]):
        return "Нежилое_помещение"

    return "Вторичное"

In [6]:
def fetch_html(url):
    response = session.get(url, timeout=30)
    return {
        "status_code": response.status_code,
        "url": response.url,
        "html": response.text
    }

In [7]:
def parse_cian_page(html, base_url):
    soup = BeautifulSoup(html, "lxml")

    text_lines = []
    for line in soup.get_text("\n").split("\n"):
        line = clean_text(line)
        if line:
            text_lines.append(line)

    rows = []
    i = 0

    while i < len(text_lines):
        line = text_lines[i]

        # ищем строку вида: "2-комн. квартира, 53,1 м², 3/10 этаж"
        if "квартира" in line.lower() and "м²" in line.lower():
            title = line
            rooms = parse_rooms(line)
            area = parse_area(line)
            floor = parse_floor(line)

            price = None
            address = None
            description = None

            # ищем цену и адрес в ближайших строках
            window = text_lines[i:i+12]

            for w in window:
                if price is None and "₽" in w:
                    price = parse_price(w)

            for w in window:
                if address is None and "челябинск" in w.lower():
                    address = w

            # описание можно взять как длинную текстовую строку
            for w in window:
                if len(w) > 80 and "₽" not in w and "челябинск" not in w.lower():
                    description = w
                    break

            rows.append({
                "Address": address,
                "Rooms": rooms,
                "Area": area,
                "Price": price,
                "Description": description,
                "Floor": floor if floor is not None else 0,
                "HousingType": detect_housing_type(" ".join(window)),
                "PhotoUrl": None,
                "Latitude": None,
                "Longitude": None,
                "Title": title,
                "Url": None,
                "RegionName": "Челябинск",
                "Source": "Cian",
                "ParsedAt": pd.Timestamp.now(),
            })

        i += 1

    df = pd.DataFrame(rows)
    return df

In [8]:
def postprocess_apartments(df):
    if df.empty:
        return df.copy()

    df = df.copy()

    df["Address"] = df["Address"].apply(clean_text)
    df["Description"] = df["Description"].apply(clean_text)
    df["Title"] = df["Title"].apply(clean_text)

    df = df[df["Price"].notna()]
    df = df[df["Area"].notna()]
    df = df[df["Rooms"].notna()]

    df["Rooms"] = df["Rooms"].astype(int)
    df["Floor"] = df["Floor"].fillna(0).astype(int)
    df["Price"] = df["Price"].astype(float)
    df["Area"] = df["Area"].astype(float)

    df = df[(df["Price"] > 0) & (df["Area"] > 0)]
    df["PricePerSqm"] = df["Price"] / df["Area"]
    df = df[df["PricePerSqm"] > 0]

    final_columns = [
        "Address",
        "Rooms",
        "Area",
        "Price",
        "Description",
        "Floor",
        "HousingType",
        "PhotoUrl",
        "Latitude",
        "Longitude",
        "Title",
        "Url",
        "RegionName",
        "Source",
        "ParsedAt",
        "PricePerSqm",
    ]

    for col in final_columns:
        if col not in df.columns:
            df[col] = None

    return df[final_columns].reset_index(drop=True)

In [9]:
result = fetch_html(BASE_URL)

print("STATUS:", result["status_code"])
print("URL:", result["url"])

html_path = os.path.join(DEBUG_BASE_DIR, "cian_chelyabinsk_debug.html")
with open(html_path, "w", encoding="utf-8") as f:
    f.write(result["html"])

print("HTML сохранён:", html_path)

df_raw = parse_cian_page(result["html"], BASE_URL)
print("RAW строк:", len(df_raw))

df_apartments = postprocess_apartments(df_raw)
print("После очистки:", len(df_apartments))

df_apartments.head(20)

STATUS: 200
URL: https://chelyabinsk.cian.ru/cian-captcha/?redirect_url=https://chelyabinsk.cian.ru/kupit-kvartiru/
HTML сохранён: data/2026/debug_cian/cian_chelyabinsk_debug.html
RAW строк: 0
После очистки: 0

Empty DataFrame
Columns: []
Index: []

In [10]:
t_now = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")

csv_path = f"{PROCESSED_BASE_DIR}/chelyabinsk_cian_apartments_{t_now}.csv"
pkl_path = f"{PROCESSED_BASE_DIR}/chelyabinsk_cian_apartments_{t_now}.pkl"

df_apartments.to_csv(csv_path, index=False, encoding="utf-8-sig")
df_apartments.to_pickle(pkl_path)

print("CSV сохранён:", csv_path)
print("PKL сохранён:", pkl_path)
print("Количество строк:", len(df_apartments))

CSV сохранён: data/2026/processed_cian/chelyabinsk_cian_apartments_2026-04-09_18-42-13.csv
PKL сохранён: data/2026/processed_cian/chelyabinsk_cian_apartments_2026-04-09_18-42-13.pkl
Количество строк: 0

In [11]:
pip install cianparser pandas

Collecting cianparser
  Downloading cianparser-1.0.4-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Collecting cloudscraper (from cianparser)
  Downloading cloudscraper-1.2.71-py2.py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (from cianparser) (4.13.5)
Collecting transliterate (from cianparser)
  Downloading transliterate-1.10.2-py2.py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (from cianparser) (6.0.2)
Collecting datetime (from cianparser)
  Downloading datetime-6.0-py3-none-any.whl.metadata (34 kB)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->cianparser) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4->cianparser) (4.15.0)
Requirement already satisfied: pyparsing>=2.4.7 in /usr/local/lib/python3.12/dist-packages (from cloudscraper->cianparser) (3.3.2)
Requirement already satisfied: requests>=2.9.2 in /usr/local/lib/python3.12/dist-packages (from cloudscraper->cianparser) (2.32.4)
Requirement already satisfied: requests-toolbelt>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from cloudscraper->cianparser) (1.0.0)
Collecting zope.interface (from datetime->cianparser)
  Downloading zope_interface-8.2-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl.metadata (45 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.4/45.4 kB 3.5 MB/s eta 0:00:00
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.9.2->cloudscraper->cianparser) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.9.2->cloudscraper->cianparser) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.9.2->cloudscraper->cianparser) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.9.2->cloudscraper->cianparser) (2026.2.25)
Downloading cianparser-1.0.4-py3-none-any.whl (32 kB)
Downloading cloudscraper-1.2.71-py2.py3-none-any.whl (99 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.7/99.7 kB 7.8 MB/s eta 0:00:00
Downloading datetime-6.0-py3-none-any.whl (52 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.6/52.6 kB 4.3 MB/s eta 0:00:00
Downloading transliterate-1.10.2-py2.py3-none-any.whl (45 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.8/45.8 kB 3.4 MB/s eta 0:00:00
Downloading zope_interface-8.2-cp312-cp312-manylinux1_x86_64.manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_5_x86_64.whl (264 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 264.9/264.9 kB 17.2 MB/s eta 0:00:00
Installing collected packages: zope.interface, transliterate, datetime, cloudscraper, cianparser
Successfully installed cianparser-1.0.4 cloudscraper-1.2.71 datetime-6.0 transliterate-1.10.2 zope.interface-8.2

In [13]:
parser = cianparser.CianParser(
    location=LOCATION,
    proxies=["http://user:pass@ip1:port", "http://user:pass@ip2:port"]
)

NameError: name 'cianparser' is not defined

In [14]:
!pip install playwright pandas beautifulsoup4 lxml

Collecting playwright
  Downloading playwright-1.58.0-py3-none-manylinux1_x86_64.whl.metadata (3.5 kB)
Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.12/dist-packages (4.13.5)
Requirement already satisfied: lxml in /usr/local/lib/python3.12/dist-packages (6.0.2)
Collecting pyee<14,>=13 (from playwright)
  Downloading pyee-13.0.1-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: greenlet<4.0.0,>=3.1.1 in /usr/local/lib/python3.12/dist-packages (from playwright) (3.3.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4) (4.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading playwright-1.58.0-py3-none-manylinux1_x86_64.whl (46.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.2/46.2 MB 13.6 MB/s eta 0:00:00
Downloading pyee-13.0.1-py3-none-any.whl (15 kB)
Installing collected packages: pyee, playwright
Successfully installed playwright-1.58.0 pyee-13.0.1

In [15]:
!playwright install chromium

Downloading Chrome for Testing 145.0.7632.6 (playwright chromium v1208) from https://cdn.playwright.dev/chrome-for-testing-public/145.0.7632.6/linux64/chrome-linux64.zip
(node:8557) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
(Use `node --trace-deprecation ...` to show where the warning was created)
167.3 MiB [] 0% 0.0s167.3 MiB [] 0% 75.0s167.3 MiB [] 0% 40.3s167.3 MiB [] 0% 27.4s167.3 MiB [] 0% 24.2s167.3 MiB [] 0% 21.9s167.3 MiB [] 0% 15.1s167.3 MiB [] 1% 7.8s167.3 MiB [] 2% 5.5s167.3 MiB [] 3% 4.2s167.3 MiB [] 4% 3.6s167.3 MiB [] 4% 3.8s167.3 MiB [] 6% 3.3s167.3 MiB [] 7% 3.0s167.3 MiB [] 8% 2.7s167.3 MiB [] 9% 2.6s167.3 MiB [] 9% 2.5s167.3 MiB [] 11% 2.3s167.3 MiB [] 12% 2.2s167.3 MiB [] 14% 2.1s167.3 MiB [] 15% 2.0s167.3 MiB [] 16% 2.0s167.3 MiB [] 17% 1.9s167.3 MiB [] 18% 1.9s167.3 MiB [] 19% 1.9s167.3 MiB [] 20% 1.9s167.3 MiB [] 21% 1.8s167.3 MiB [] 22% 1.8s167.3 MiB [] 23% 1.8s167.3 MiB [] 24% 1.8s167.3 MiB [] 25% 1.8s167.3 MiB [] 26% 1.7s167.3 MiB [] 27% 1.7s167.3 MiB [] 28% 1.7s167.3 MiB [] 29% 1.7s167.3 MiB [] 30% 1.6s167.3 MiB [] 31% 1.6s167.3 MiB [] 31% 1.7s167.3 MiB [] 33% 1.6s167.3 MiB [] 34% 1.6s167.3 MiB [] 35% 1.6s167.3 MiB [] 36% 1.6s167.3 MiB [] 37% 1.5s167.3 MiB [] 38% 1.5s167.3 MiB [] 39% 1.5s167.3 MiB [] 40% 1.4s167.3 MiB [] 41% 1.4s167.3 MiB [] 42% 1.4s167.3 MiB [] 43% 1.4s167.3 MiB [] 44% 1.4s167.3 MiB [] 45% 1.4s167.3 MiB [] 46% 1.4s167.3 MiB [] 47% 1.4s167.3 MiB [] 48% 1.4s167.3 MiB [] 49% 1.4s167.3 MiB [] 50% 1.3s167.3 MiB [] 51% 1.3s167.3 MiB [] 52% 1.3s167.3 MiB [] 53% 1.3s167.3 MiB [] 54% 1.3s167.3 MiB [] 55% 1.3s167.3 MiB [] 56% 1.2s167.3 MiB [] 57% 1.2s167.3 MiB [] 58% 1.2s167.3 MiB [] 59% 1.2s167.3 MiB [] 60% 1.2s167.3 MiB [] 61% 1.2s167.3 MiB [] 62% 1.2s167.3 MiB [] 63% 1.2s167.3 MiB [] 64% 1.2s167.3 MiB [] 65% 1.2s167.3 MiB [] 66% 1.2s167.3 MiB [] 67% 1.2s167.3 MiB [] 67% 1.1s167.3 MiB [] 68% 1.1s167.3 MiB [] 69% 1.1s167.3 MiB [] 70% 1.1s167.3 MiB [] 70% 1.0s167.3 MiB [] 71% 1.0s167.3 MiB [] 72% 1.0s167.3 MiB [] 73% 1.0s167.3 MiB [] 74% 1.0s167.3 MiB [] 74% 0.9s167.3 MiB [] 75% 0.9s167.3 MiB [] 76% 0.9s167.3 MiB [] 77% 0.9s167.3 MiB [] 78% 0.9s167.3 MiB [] 78% 0.8s167.3 MiB [] 79% 0.8s167.3 MiB [] 80% 0.8s167.3 MiB [] 81% 0.8s167.3 MiB [] 82% 0.7s167.3 MiB [] 83% 0.7s167.3 MiB [] 84% 0.7s167.3 MiB [] 84% 0.6s167.3 MiB [] 85% 0.6s167.3 MiB [] 86% 0.6s167.3 MiB [] 87% 0.6s167.3 MiB [] 87% 0.5s167.3 MiB [] 88% 0.5s167.3 MiB [] 89% 0.5s167.3 MiB [] 89% 0.4s167.3 MiB [] 90% 0.4s167.3 MiB [] 91% 0.4s167.3 MiB [] 92% 0.3s167.3 MiB [] 93% 0.3s167.3 MiB [] 94% 0.3s167.3 MiB [] 94% 0.2s167.3 MiB [] 95% 0.2s167.3 MiB [] 96% 0.2s167.3 MiB [] 96% 0.1s167.3 MiB [] 97% 0.1s167.3 MiB [] 98% 0.1s167.3 MiB [] 99% 0.0s167.3 MiB [] 100% 0.0s
Chrome for Testing 145.0.7632.6 (playwright chromium v1208) downloaded to /root/.cache/ms-playwright/chromium-1208
Downloading FFmpeg (playwright ffmpeg v1011) from https://cdn.playwright.dev/dbazure/download/playwright/builds/ffmpeg/1011/ffmpeg-linux.zip
(node:8644) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
(Use `node --trace-deprecation ...` to show where the warning was created)
2.3 MiB [] 0% 0.0s2.3 MiB [] 22% 0.1s2.3 MiB [] 54% 0.0s2.3 MiB [] 86% 0.0s2.3 MiB [] 100% 0.0s
FFmpeg (playwright ffmpeg v1011) downloaded to /root/.cache/ms-playwright/ffmpeg-1011
Downloading Chrome Headless Shell 145.0.7632.6 (playwright chromium-headless-shell v1208) from https://cdn.playwright.dev/chrome-for-testing-public/145.0.7632.6/linux64/chrome-headless-shell-linux64.zip
(node:8659) [DEP0169] DeprecationWarning: `url.parse()` behavior is not standardized and prone to errors that have security implications. Use the WHATWG URL API instead. CVEs are not issued for `url.parse()` vulnerabilities.
(Use `node --trace-deprecation ...` to show where the warning was created)
110.9 MiB [] 0% 0.0s110.9 MiB [] 0% 29.1s110.9 MiB [] 0% 9.9s110.9 MiB [] 0% 7.3s110.9 MiB [] 1% 3.6s110.9 MiB [] 3% 2.6s110.9 MiB [] 4% 2.0s110.9 MiB [] 5% 1.9s110.9 MiB [] 7% 1.7s110.9 MiB [] 8% 1.6s110.9 MiB [] 9% 1.7s110.9 MiB [] 9% 1.8s110.9 MiB [] 9% 2.0s110.9 MiB [] 11% 1.8s110.9 MiB [] 12% 1.7s110.9 MiB [] 14% 1.6s110.9 MiB [] 16% 1.4s110.9 MiB [] 18% 1.3s110.9 MiB [] 19% 1.3s110.9 MiB [] 20% 1.3s110.9 MiB [] 21% 1.2s110.9 MiB [] 22% 1.2s110.9 MiB [] 23% 1.2s110.9 MiB [] 25% 1.2s110.9 MiB [] 26% 1.1s110.9 MiB [] 28% 1.1s110.9 MiB [] 30% 1.0s110.9 MiB [] 31% 1.0s110.9 MiB [] 33% 1.0s110.9 MiB [] 35% 0.9s110.9 MiB [] 37% 0.8s110.9 MiB [] 39% 0.8s110.9 MiB [] 41% 0.7s110.9 MiB [] 43% 0.7s110.9 MiB [] 45% 0.7s110.9 MiB [] 47% 0.6s110.9 MiB [] 50% 0.6s110.9 MiB [] 52% 0.6s110.9 MiB [] 54% 0.5s110.9 MiB [] 56% 0.5s110.9 MiB [] 58% 0.5s110.9 MiB [] 59% 0.5s110.9 MiB [] 60% 0.5s110.9 MiB [] 61% 0.5s110.9 MiB [] 62% 0.4s110.9 MiB [] 63% 0.4s110.9 MiB [] 64% 0.4s110.9 MiB [] 65% 0.4s110.9 MiB [] 66% 0.4s110.9 MiB [] 67% 0.4s110.9 MiB [] 68% 0.4s110.9 MiB [] 69% 0.4s110.9 MiB [] 70% 0.4s110.9 MiB [] 71% 0.4s110.9 MiB [] 73% 0.3s110.9 MiB [] 74% 0.3s110.9 MiB [] 76% 0.3s110.9 MiB [] 78% 0.3s110.9 MiB [] 80% 0.2s110.9 MiB [] 82% 0.2s110.9 MiB [] 84% 0.2s110.9 MiB [] 86% 0.2s110.9 MiB [] 88% 0.1s110.9 MiB [] 89% 0.1s110.9 MiB [] 91% 0.1s110.9 MiB [] 92% 0.1s110.9 MiB [] 94% 0.1s110.9 MiB [] 96% 0.0s110.9 MiB [] 97% 0.0s110.9 MiB [] 98% 0.0s110.9 MiB [] 99% 0.0s110.9 MiB [] 100% 0.0s
Chrome Headless Shell 145.0.7632.6 (playwright chromium-headless-shell v1208) downloaded to /root/.cache/ms-playwright/chromium_headless_shell-1208

In [16]:
import nest_asyncio
nest_asyncio.apply()

In [18]:
import re
import pandas as pd
import asyncio
import time
import random
import nest_asyncio
from datetime import datetime
from bs4 import BeautifulSoup
from playwright.async_api import async_playwright

In [20]:
!apt-get update -y
!apt-get install -y \
    libatk1.0-0 \
    libatk-bridge2.0-0 \
    libcups2 \
    libxcomposite1 \
    libxdamage1 \
    libxfixes3 \
    libxrandr2 \
    libgbm1 \
    libxkbcommon0 \
    libpango-1.0-0 \
    libcairo2 \
    libasound2 \
    libnss3 \
    libnspr4 \
    libgtk-3-0 \
    libdrm2 \
    libxshmfence1

!pip install -q playwright
!playwright install chromium

Get:1 http://security.ubuntu.com/ubuntu jammy-security InRelease [129 kB]
Get:2 https://cli.github.com/packages stable InRelease [3,917 B]
Get:3 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,632 B]
Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:5 https://r2u.stat.illinois.edu/ubuntu jammy InRelease [6,555 B]
Get:6 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [128 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [127 kB]
Get:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease [18.1 kB]
Hit:9 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:10 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [6,917 kB]
Get:11 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,311 kB]
Get:12 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ Packages [88.5 kB]
Get:13 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [3,889 kB]
Get:14 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [2,964 kB]
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1,622 kB]
Get:16 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [9,998 kB]
Get:17 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy/main amd64 Packages [38.8 kB]
Get:18 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [7,143 kB]
Get:19 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [4,226 kB]
Fetched 38.6 MB in 5s (7,093 kB/s)
Reading package lists... Done
W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu jammy InRelease' does not seem to provide it (sources.list entry misspelt?)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libxdamage1 is already the newest version (1:1.1.5-2build2).
libxdamage1 set to manually installed.
libxfixes3 is already the newest version (1:6.0.0-1).
libxfixes3 set to manually installed.
libxkbcommon0 is already the newest version (1.4.0-1).
libxkbcommon0 set to manually installed.
libxrandr2 is already the newest version (2:1.5.2-1build1).
libxrandr2 set to manually installed.
libxshmfence1 is already the newest version (1.3-1build4).
libxshmfence1 set to manually installed.
libasound2 is already the newest version (1.2.6.1-1ubuntu1.1).
libasound2 set to manually installed.
libcairo2 is already the newest version (1.16.0-5ubuntu2.1).
libcairo2 set to manually installed.
libcups2 is already the newest version (2.4.1op1-1ubuntu4.16).
libcups2 set to manually installed.
libdrm2 is already the newest version (2.4.113-2~ubuntu0.22.04.1).
libdrm2 set to manually installed.
libgbm1 is already the newest version (23.2.1-1ubuntu3.1~22.04.3).
libgbm1 set to manually installed.
libnspr4 is already the newest version (2:4.35-0ubuntu0.22.04.1).
libnspr4 set to manually installed.
libnss3 is already the newest version (2:3.98-0ubuntu0.22.04.3).
libnss3 set to manually installed.
libpango-1.0-0 is already the newest version (1.50.6+ds-2ubuntu1).
libpango-1.0-0 set to manually installed.
The following additional packages will be installed:
  at-spi2-core gsettings-desktop-schemas libatk1.0-data libatspi2.0-0
  libgtk-3-bin libgtk-3-common librsvg2-common libxtst6 session-migration
Suggested packages:
  gvfs
The following NEW packages will be installed:
  at-spi2-core gsettings-desktop-schemas libatk-bridge2.0-0 libatk1.0-0
  libatk1.0-data libatspi2.0-0 libgtk-3-0 libgtk-3-bin libgtk-3-common
  librsvg2-common libxcomposite1 libxtst6 session-migration
0 upgraded, 13 newly installed, 0 to remove and 22 not upgraded.
Need to get 3,697 kB of archives.
After this operation, 12.9 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatspi2.0-0 amd64 2.44.0-3 [80.9 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxtst6 amd64 2:1.2.3-1build4 [13.4 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 session-migration amd64 0.3.6 [9,774 B]
Get:4 http://archive.ubuntu.com/ubuntu jammy/main amd64 gsettings-desktop-schemas all 42.0-1ubuntu1 [31.1 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy/main amd64 at-spi2-core amd64 2.44.0-3 [54.4 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk1.0-data all 2.36.0-3build1 [2,824 B]
Get:7 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk1.0-0 amd64 2.36.0-3build1 [51.9 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy/main amd64 libatk-bridge2.0-0 amd64 2.38.0-3 [66.6 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy/main amd64 libxcomposite1 amd64 1:0.4.5-1build2 [7,192 B]
Get:10 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgtk-3-common all 3.24.33-1ubuntu2.2 [239 kB]
Get:11 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgtk-3-0 amd64 3.24.33-1ubuntu2.2 [3,053 kB]
Get:12 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgtk-3-bin amd64 3.24.33-1ubuntu2.2 [69.6 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 librsvg2-common amd64 2.52.5+dfsg-3ubuntu0.2 [17.7 kB]
Fetched 3,697 kB in 0s (18.7 MB/s)
Selecting previously unselected package libatspi2.0-0:amd64.
(Reading database ... 118194 files and directories currently installed.)
Preparing to unpack .../00-libatspi2.0-0_2.44.0-3_amd64.deb ...
Unpacking libatspi2.0-0:amd64 (2.44.0-3) ...
Selecting previously unselected package libxtst6:amd64.
Preparing to unpack .../01-libxtst6_2%3a1.2.3-1build4_amd64.deb ...
Unpacking libxtst6:amd64 (2:1.2.3-1build4) ...
Selecting previously unselected package session-migration.
Preparing to unpack .../02-session-migration_0.3.6_amd64.deb ...
Unpacking session-migration (0.3.6) ...
Selecting previously unselected package gsettings-desktop-schemas.
Preparing to unpack .../03-gsettings-desktop-schemas_42.0-1ubuntu1_all.deb ...
Unpacking gsettings-desktop-schemas (42.0-1ubuntu1) ...
Selecting previously unselected package at-spi2-core.
Preparing to unpack .../04-at-spi2-core_2.44.0-3_amd64.deb ...
Unpacking at-spi2-core (2.44.0-3) ...
Selecting previously unselected package libatk1.0-data.
Preparing to unpack .../05-libatk1.0-data_2.36.0-3build1_all.deb ...
Unpacking libatk1.0-data (2.36.0-3build1) ...
Selecting previously unselected package libatk1.0-0:amd64.
Preparing to unpack .../06-libatk1.0-0_2.36.0-3build1_amd64.deb ...
Unpacking libatk1.0-0:amd64 (2.36.0-3build1) ...
Selecting previously unselected package libatk-bridge2.0-0:amd64.
Preparing to unpack .../07-libatk-bridge2.0-0_2.38.0-3_amd64.deb ...
Unpacking libatk-bridge2.0-0:amd64 (2.38.0-3) ...
Selecting previously unselected package libxcomposite1:amd64.
Preparing to unpack .../08-libxcomposite1_1%3a0.4.5-1build2_amd64.deb ...
Unpacking libxcomposite1:amd64 (1:0.4.5-1build2) ...
Selecting previously unselected package libgtk-3-common.
Preparing to unpack .../09-libgtk-3-common_3.24.33-1ubuntu2.2_all.deb ...
Unpacking libgtk-3-common (3.24.33-1ubuntu2.2) ...
Selecting previously unselected package libgtk-3-0:amd64.
Preparing to unpack .../10-libgtk-3-0_3.24.33-1ubuntu2.2_amd64.deb ...
Unpacking libgtk-3-0:amd64 (3.24.33-1ubuntu2.2) ...
Selecting previously unselected package libgtk-3-bin.
Preparing to unpack .../11-libgtk-3-bin_3.24.33-1ubuntu2.2_amd64.deb ...
Unpacking libgtk-3-bin (3.24.33-1ubuntu2.2) ...
Selecting previously unselected package librsvg2-common:amd64.
Preparing to unpack .../12-librsvg2-common_2.52.5+dfsg-3ubuntu0.2_amd64.deb ...
Unpacking librsvg2-common:amd64 (2.52.5+dfsg-3ubuntu0.2) ...
Setting up session-migration (0.3.6) ...
Created symlink /etc/systemd/user/graphical-session-pre.target.wants/session-migration.service → /usr/lib/systemd/user/session-migration.service.
Setting up libxtst6:amd64 (2:1.2.3-1build4) ...
Setting up libatspi2.0-0:amd64 (2.44.0-3) ...
Setting up librsvg2-common:amd64 (2.52.5+dfsg-3ubuntu0.2) ...
Setting up libatk1.0-data (2.36.0-3build1) ...
Setting up libatk1.0-0:amd64 (2.36.0-3build1) ...
Setting up libxcomposite1:amd64 (1:0.4.5-1build2) ...
Setting up libgtk-3-common (3.24.33-1ubuntu2.2) ...
Setting up gsettings-desktop-schemas (42.0-1ubuntu1) ...
Setting up libatk-bridge2.0-0:amd64 (2.38.0-3) ...
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libgdk-pixbuf-2.0-0:amd64 (2.42.8+dfsg-1ubuntu0.4) ...
Processing triggers for libglib2.0-0:amd64 (2.72.4-0ubuntu2.9) ...
Setting up libgtk-3-0:amd64 (3.24.33-1ubuntu2.2) ...
Processing triggers for libc-bin (2.35-0ubuntu3.13) ...
/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libumf.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_level_zero_v2.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_adapter_opencl.so.0 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libhwloc.so.15 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtcm_debug.so.1 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libur_loader.so.0 is not a symbolic link

Setting up libgtk-3-bin (3.24.33-1ubuntu2.2) ...
Setting up at-spi2-core (2.44.0-3) ...

РАБОЧИЙ ВАРИАНТ!!!!

In [23]:
import re
import os
import pandas as pd
import asyncio
import random
import nest_asyncio
from datetime import datetime
from bs4 import BeautifulSoup
from playwright.async_api import async_playwright

nest_asyncio.apply()
os.makedirs("data/2026/processed", exist_ok=True)
os.makedirs("data/2026/debug_pages", exist_ok=True)

# СКОЛЬКО СТРАНИЦ ПАРСИТЬ МАКСИМУМ
MAX_PAGES_PER_CATEGORY = 50


def clean_text(s):
    return re.sub(r"\s+", " ", str(s)).strip() if s else None


def clean_price(text):
    if not text:
        return None
    text = str(text).replace("\xa0", " ")

    m = re.search(r"([\d\s]+)\s*₽", text)
    if m:
        digits = re.sub(r"\D", "", m.group(1))
        try:
            return int(digits)
        except:
            pass

    m = re.search(r"(\d+(?:[.,]\d+)?)\s*млн", text.lower())
    if m:
        try:
            return int(float(m.group(1).replace(",", ".")) * 1_000_000)
        except:
            pass

    m = re.search(r"(\d+(?:[.,]\d+)?)\s*тыс", text.lower())
    if m:
        try:
            return int(float(m.group(1).replace(",", ".")) * 1_000)
        except:
            pass

    digits = re.sub(r"\D", "", text)
    try:
        return int(digits) if digits else None
    except:
        return None


def parse_title_info(title):
    if not title:
        return 1, None, 0

    rooms = 1
    area = None
    floor = 0
    title_lower = title.lower()

    m = re.search(r"(\d+)-комн", title_lower)
    if m:
        rooms = int(m.group(1))
    elif "студ" in title_lower:
        rooms = 0

    m = re.search(r"(\d+[.,]?\d*)\s*м²", title)
    if m:
        area = float(m.group(1).replace(",", "."))

    m = re.search(r"(\d+)/(\d+)\s*этаж", title_lower)
    if m:
        floor = int(m.group(1))

    return rooms, area, floor


def parse_area(text):
    if not text:
        return None
    m = re.search(r"(\d+(?:[.,]\d+)?)\s*м²", text.lower())
    if m:
        return float(m.group(1).replace(",", "."))
    return None


def parse_floor(text):
    if not text:
        return 0

    m = re.search(r"(\d+)/(\d+)\s*этаж", text.lower())
    if m:
        return int(m.group(1))

    m = re.search(r"этаж[:\s]+(\d+)", text.lower())
    if m:
        return int(m.group(1))

    m = re.search(r"этаж\s*(\d+)", text.lower())
    if m:
        return int(m.group(1))

    return 0


def looks_like_address_part(text):
    if not text:
        return False

    t = text.lower().strip()
    address_keywords = [
        "челябинск",
        "челябинская область",
        "р-н",
        "район",
        "улица",
        "ул.",
        "проспект",
        "пр-кт",
        "переулок",
        "пер.",
        "бульвар",
        "мкр.",
        "микрорайон",
        "пос.",
        "поселок",
        "шоссе",
        "тракт",
        "площадь",
        "наб.",
        "набережная",
    ]

    if any(k in t for k in address_keywords):
        return True

    if re.fullmatch(r"\d+[а-яa-z\-\/]*", t):
        return True

    return False


def normalize_address_parts(parts):
    cleaned = []
    seen = set()

    for p in parts:
        p = clean_text(p)
        if not p:
            continue

        low = p.lower()
        bad_starts = [
            "ещё фото",
            "еще фото",
            "только на циан",
            "хорошая цена",
            "документы проверены",
            "проверено в росреестре",
            "агентство недвижимости",
            "написать",
            "позвонить",
            "сохранить",
            "id ",
            "отчёт по объекту",
            "отчет по объекту",
            "показать телефон",
        ]

        if any(low.startswith(x) for x in bad_starts):
            continue

        if "₽" in p:
            continue

        if p not in seen:
            seen.add(p)
            cleaned.append(p)

    if not cleaned:
        return "Челябинск"

    address = ", ".join(cleaned)
    if "челябинск" not in address.lower():
        address = "Челябинск, " + address

    return address


def extract_address_from_card(card, title=None):
    candidate_texts = []

    for node in card.select("a, span, div"):
        txt = clean_text(node.get_text(" ", strip=True))
        if txt and looks_like_address_part(txt):
            candidate_texts.append(txt)

    address = normalize_address_parts(candidate_texts)
    if address != "Челябинск":
        return address

    parts = [clean_text(x) for x in card.stripped_strings]
    parts = [x for x in parts if x]

    start_idx = 0
    if title and title in parts:
        start_idx = parts.index(title) + 1

    buf = []
    for part in parts[start_idx:start_idx + 30]:
        if "₽" in part or "млн" in part.lower() or "тыс" in part.lower():
            break
        if looks_like_address_part(part):
            buf.append(part)
        elif buf:
            break

    return normalize_address_parts(buf)


def extract_title(card):
    selectors = [
        'span[data-mark="OfferTitle"]',
        'div[class*="title"]',
        "h3",
        'a[href*="/sale/flat/"]',
    ]

    for sel in selectors:
        tag = card.select_one(sel)
        if tag:
            txt = clean_text(tag.get_text(" ", strip=True))
            if txt:
                return txt

    parts = [clean_text(x) for x in card.stripped_strings if clean_text(x)]
    if not parts:
        return ""

    return parts[0]


def extract_link(card):
    for sel in ['a[href*="/sale/flat/"]', "a[href]"]:
        tag = card.select_one(sel)
        if tag and tag.has_attr("href"):
            href = tag["href"]
            if href.startswith("http"):
                return href
            if href.startswith("/"):
                return "https://chelyabinsk.cian.ru" + href
    return None


def extract_price(card, full_text):
    selectors = [
        'span[data-mark="MainPrice"]',
        'div[data-mark="MainPrice"]',
        '[class*="price"]'
    ]

    for sel in selectors:
        tag = card.select_one(sel)
        if tag:
            price = clean_price(tag.get_text(" ", strip=True))
            if price:
                return price

    for p in [clean_text(x) for x in card.stripped_strings if clean_text(x)]:
        if "₽" in p or "млн" in p.lower() or "тыс" in p.lower():
            price = clean_price(p)
            if price:
                return price

    return clean_price(full_text)


def extract_card_links(soup):
    links = []

    for a in soup.select('a[href*="/sale/flat/"]'):
        href = a.get("href")
        if not href:
            continue

        if href.startswith("/"):
            href = "https://chelyabinsk.cian.ru" + href

        links.append(href)

    uniq = []
    seen = set()
    for link in links:
        if link not in seen:
            seen.add(link)
            uniq.append(link)

    return uniq


async def scrape_cian_flats():
    all_data = []
    global_seen_links = set()

    base_url = "https://chelyabinsk.cian.ru/kupit-kvartiru/"

    async with async_playwright() as p:
        browser = await p.chromium.launch(
            headless=True,
            args=[
                "--no-sandbox",
                "--disable-setuid-sandbox",
                "--disable-dev-shm-usage",
                "--disable-gpu"
            ]
        )

        context = await browser.new_context(
            user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/134.0.0.0 Safari/537.36",
            viewport={"width": 1366, "height": 768},
            locale="ru-RU"
        )

        page = await context.new_page()

        print(f"\n🚀 Парсим квартиры (макс. {MAX_PAGES_PER_CATEGORY} страниц)...")

        await page.goto(base_url, wait_until="domcontentloaded", timeout=90000)
        await asyncio.sleep(random.uniform(4, 7))

        previous_page_links = None

        for page_num in range(1, MAX_PAGES_PER_CATEGORY + 1):
            print(f"\n--- Страница {page_num} ---")
            print("URL:", page.url)

            try:
                await page.evaluate("window.scrollTo(0, document.body.scrollHeight * 0.5)")
                await asyncio.sleep(random.uniform(2, 4))
                await page.evaluate("window.scrollTo(0, document.body.scrollHeight)")
                await asyncio.sleep(random.uniform(3, 5))

                html = await page.content()

                debug_file = f"data/2026/debug_pages/flats_page_{page_num}.html"
                with open(debug_file, "w", encoding="utf-8") as f:
                    f.write(html)

                soup = BeautifulSoup(html, "lxml")

                page_links = extract_card_links(soup)
                print(f"     -> найдено ссылок карточек: {len(page_links)}")

                if previous_page_links is not None and set(page_links) == set(previous_page_links):
                    print("     ⚠️ Ссылки совпали с предыдущей страницей. Останавливаемся.")
                    break

                previous_page_links = page_links

                cards = soup.select(
                    'article[data-name="CardComponent"], '
                    'div[data-name="CardComponent"]'
                )

                print(f"     -> найдено карточек по селектору: {len(cards)}")

                added = 0

                for card in cards:
                    try:
                        full_text = " ".join(
                            [clean_text(x) for x in card.stripped_strings if clean_text(x)]
                        )

                        if not full_text or len(full_text) < 40:
                            continue

                        if "квартира" not in full_text.lower() and "студия" not in full_text.lower():
                            continue

                        title = extract_title(card)
                        address = extract_address_from_card(card, title)
                        url_item = extract_link(card)

                        rooms, area, floor = parse_title_info(title)

                        if area is None:
                            area = parse_area(full_text)

                        if floor == 0:
                            floor = parse_floor(full_text)

                        price = extract_price(card, full_text)

                        if price is None or area is None or area < 15:
                            continue

                        housing_type = "Новостройка" if any(
                            x in full_text.lower()
                            for x in ["жк", "новостройк", "от застройщика", "сдача корпуса", "дом сдан"]
                        ) else "Вторичное"

                        if url_item and url_item in global_seen_links:
                            continue
                        if url_item:
                            global_seen_links.add(url_item)

                        all_data.append({
                            "Address": address,
                            "Rooms": int(rooms) if rooms is not None else 1,
                            "Area": float(area),
                            "Price": int(price),
                            "Description": title if title else full_text[:300],
                            "Floor": int(floor) if floor is not None else 0,
                            "HousingType": housing_type,
                            "Latitude": None,
                            "Longitude": None,
                            "RegionName": "Челябинск",
                            "Source": "Cian",
                            "Url": url_item,
                            "ParsedAt": pd.Timestamp.now(),
                        })
                        added += 1

                    except Exception:
                        continue

                print(f"     -> добавлено новых объявлений: {added}")
                print(f"     -> всего уникальных ссылок: {len(global_seen_links)}")

                if page_num >= MAX_PAGES_PER_CATEGORY:
                    break

                next_btn = page.get_by_role("link", name="Дальше")

                if await next_btn.count() == 0:
                    next_btn = page.locator("a").filter(has_text="Дальше")

                if await next_btn.count() == 0:
                    print("     -> Кнопка 'Дальше' не найдена. Похоже, страницы закончились.")
                    break

                old_url = page.url
                old_links = set(page_links)

                await next_btn.first.scroll_into_view_if_needed()
                await asyncio.sleep(1)
                await next_btn.first.click(timeout=30000)
                await asyncio.sleep(random.uniform(4, 7))

                changed = False
                for _ in range(10):
                    await asyncio.sleep(1.5)
                    new_html = await page.content()
                    new_soup = BeautifulSoup(new_html, "lxml")
                    new_links = set(extract_card_links(new_soup))

                    if page.url != old_url or new_links != old_links:
                        changed = True
                        break

                if not changed:
                    print("     ⚠️ После нажатия 'Дальше' страница не изменилась. Останавливаемся.")
                    break

            except Exception as e:
                print(f"     ❌ Ошибка на странице {page_num}: {e}")
                break

        await page.close()
        await browser.close()

    df = pd.DataFrame(all_data)

    if not df.empty:
        df = df.dropna(subset=["Price", "Area"])
        df = df[df["Area"] > 0]
        df["PricePerSqm"] = df["Price"] / df["Area"]
    else:
        df["PricePerSqm"] = pd.Series(dtype=float)

    print(f"\n✅ ВСЕГО собрано квартир: {len(df)}")

    t_now = datetime.now().strftime("%Y-%m-%d_%H-%M")
    path = f"data/2026/processed/cian_flats_{len(df)}_{t_now}"
    df.to_csv(f"{path}.csv", index=False, encoding="utf-8-sig")
    df.to_pickle(f"{path}.pkl")

    print(f"\nФайлы сохранены:")
    print(f" - {path}.csv")
    print(f" - {path}.pkl")

    return df


# ===================== ЗАПУСК =====================
df = await scrape_cian_flats()

display(df[["Address", "Price", "Area", "Rooms", "Floor", "HousingType", "Url"]].head(20))
print("\nРаспределение по типам:")
print(df["HousingType"].value_counts())

🚀 Парсим квартиры (макс. 50 страниц)...

--- Страница 1 ---
URL: https://chelyabinsk.cian.ru/kupit-kvartiru/
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 28

--- Страница 2 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=2&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 56

--- Страница 3 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=3&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 84

--- Страница 4 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=4&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 112

--- Страница 5 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=5&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 27
     -> всего уникальных ссылок: 139

--- Страница 6 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=6&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 167

--- Страница 7 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=7&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 195

--- Страница 8 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=8&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 223

--- Страница 9 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=9&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 251

--- Страница 10 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=10&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 279

--- Страница 11 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=11&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 307

--- Страница 12 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=12&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 335

--- Страница 13 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=13&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 363

--- Страница 14 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=14&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 391

--- Страница 15 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=15&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 419

--- Страница 16 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=16&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 447

--- Страница 17 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=17&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 475

--- Страница 18 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=18&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 503

--- Страница 19 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=19&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 531

--- Страница 20 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=20&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 559

--- Страница 21 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=21&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 587

--- Страница 22 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=22&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 615

--- Страница 23 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=23&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 643

--- Страница 24 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=24&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 671

--- Страница 25 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=25&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 699

--- Страница 26 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=26&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 727

--- Страница 27 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=27&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 755

--- Страница 28 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=28&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 783

--- Страница 29 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=29&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 811

--- Страница 30 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=30&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 839

--- Страница 31 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=31&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 867

--- Страница 32 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=32&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 895

--- Страница 33 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=33&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 923

--- Страница 34 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=34&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 951

--- Страница 35 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=35&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 979

--- Страница 36 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=36&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 1007

--- Страница 37 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=37&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 1035

--- Страница 38 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=38&region=5048
     -> найдено ссылок карточек: 27
     -> найдено карточек по селектору: 27
     -> добавлено новых объявлений: 26
     -> всего уникальных ссылок: 1061

--- Страница 39 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=39&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 27
     -> всего уникальных ссылок: 1088

--- Страница 40 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=40&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 27
     -> всего уникальных ссылок: 1115

--- Страница 41 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=41&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 1143

--- Страница 42 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=42&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 1171

--- Страница 43 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=43&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 1199

--- Страница 44 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=44&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 27
     -> всего уникальных ссылок: 1226

--- Страница 45 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=45&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 1254

--- Страница 46 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=46&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 1282

--- Страница 47 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=47&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 1310

--- Страница 48 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=48&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 1338

--- Страница 49 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=49&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 1366

--- Страница 50 ---
URL: https://chelyabinsk.cian.ru/cat.php?deal_type=sale&engine_version=2&offer_type=flat&p=50&region=5048
     -> найдено ссылок карточек: 28
     -> найдено карточек по селектору: 28
     -> добавлено новых объявлений: 28
     -> всего уникальных ссылок: 1394

✅ ВСЕГО собрано квартир: 1394

Файлы сохранены:
 - data/2026/processed/cian_flats_1394_2026-04-09_19-23.csv
 - data/2026/processed/cian_flats_1394_2026-04-09_19-23.pkl

,Address,Price,Area,Rooms,Floor,HousingType,Url
0,ЖК «Апартаменты ГОЛОС в сердце города» дом сда...,55552800,234.40,1,26,Новостройка,https://chelyabinsk.cian.ru/sale/flat/32792925...
1,"Челябинская область , Челябинск , р-н Тракторо...",3280000,40.70,2,5,Вторичное,https://chelyabinsk.cian.ru/sale/flat/32307934...
2,"ЖК «Квартал О2» Челябинская область , Челябинс...",6100000,56.20,2,4,Новостройка,https://chelyabinsk.cian.ru/sale/flat/32073443...
3,"ЖК «Клевер» Челябинская область , Челябинск , ...",7359800,42.35,1,4,Новостройка,https://chelyabinsk.cian.ru/sale/flat/32864421...
4,"Челябинская область , Челябинск , р-н Ленински...",5890000,68.00,3,10,Вторичное,https://chelyabinsk.cian.ru/sale/flat/32330431...
5,"Челябинская область , Челябинск , р-н Ленински...",4900000,61.50,3,5,Вторичное,https://chelyabinsk.cian.ru/sale/flat/31615722...
6,"ЖК «Клевер» Челябинская область , Челябинск , ...",9123800,59.80,2,3,Новостройка,https://chelyabinsk.cian.ru/sale/flat/32753317...
7,"Челябинская область , Челябинск , р-н Централь...",10400000,65.30,3,5,Вторичное,https://chelyabinsk.cian.ru/sale/flat/32852076...
8,"Челябинская область , Челябинск , р-н Тракторо...",6000000,53.30,2,4,Вторичное,https://chelyabinsk.cian.ru/sale/flat/31045917...
9,"ЖК «Клевер» Челябинская область , Челябинск , ...",8369200,53.10,2,3,Новостройка,https://chelyabinsk.cian.ru/sale/flat/32489644...
10,"Челябинская область , Челябинск , р-н Курчатов...",3750000,45.30,2,4,Вторичное,https://chelyabinsk.cian.ru/sale/flat/32513361...
11,"Челябинская область , Челябинск , р-н Тракторо...",5600000,50.00,1,2,Вторичное,https://chelyabinsk.cian.ru/sale/flat/32787209...
12,"ЖК «Клевер» Челябинская область , Челябинск , ...",18720000,95.34,3,10,Новостройка,https://chelyabinsk.cian.ru/sale/flat/31980965...
13,"Челябинская область , Челябинск , р-н Калининс...",3800000,36.50,1,8,Вторичное,https://chelyabinsk.cian.ru/sale/flat/32695392...
14,"Челябинская область , Челябинск , р-н Советски...",2250000,30.40,1,2,Вторичное,https://chelyabinsk.cian.ru/sale/flat/32769340...
15,"ЖК «Большой» Челябинская область , Челябинск ,...",16260000,56.57,1,2,Новостройка,https://chelyabinsk.cian.ru/sale/flat/31617854...
16,"ЖК «Новое поколение» Челябинская область , Чел...",5200000,45.00,1,11,Новостройка,https://chelyabinsk.cian.ru/sale/flat/32779197...
17,"Челябинская область , Челябинск , р-н Советски...",8590000,88.70,4,4,Вторичное,https://chelyabinsk.cian.ru/sale/flat/32073320...
18,"ЖК «Большой» Челябинская область , Челябинск ,...",26090000,101.49,2,3,Новостройка,https://chelyabinsk.cian.ru/sale/flat/32412808...
19,"Челябинская область , Челябинск , р-н Курчатов...",15990000,97.70,1,2,Вторичное,https://chelyabinsk.cian.ru/sale/flat/32466450...

Распределение по типам:
HousingType
Новостройка    811
Вторичное      583
Name: count, dtype: int64

In [ ]:
!pip install geopy -q

In [ ]:
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter
import re

geolocator = Nominatim(user_agent="cian_parser_ml_final", timeout=10)
geocode = RateLimiter(geolocator.geocode, min_delay_seconds=1.1)

def extract_house_number(text):
    if not text:
        return None
    patterns = [
        r'(?:д\.?|дом|д)\s*(\d+[а-яА-Яa-zA-Z/\\-]*)',
        r'\b(\d+[а-яА-Яa-zA-Z/\\-]*)\s*(?:кв|комн|эт)',
        r'\b(\d+[а-яА-Яa-zA-Z/\\-]*)\b$'
    ]
    for pat in patterns:
        m = re.search(pat, text, re.IGNORECASE)
        if m:
            return m.group(1)
    return None

def build_smart_address(row):
    addr = str(row["Address"]).strip()
    title = str(row.get("Title") or row.get("Description") or "")

    house = extract_house_number(title)

    # Формируем несколько вариантов адреса
    variants = []

    if house:
        variants.append(f"{addr}, д. {house}, Челябинск, Челябинская область, Россия")

    variants.append(f"{addr}, Челябинск, Челябинская область, Россия")
    variants.append(f"Челябинск, {addr}, Челябинская область, Россия")

    return variants

print("🔄 Финальное улучшенное геокодирование...")

df["Latitude"] = None
df["Longitude"] = None

for idx, row in df.iterrows():
    variants = build_smart_address(row)
    lat = lon = None

    for addr_variant in variants:
        try:
            location = geocode(addr_variant)
            if location:
                lat = round(location.latitude, 6)
                lon = round(location.longitude, 6)
                break
        except:
            continue

    df.at[idx, "Latitude"] = lat
    df.at[idx, "Longitude"] = lon

    if (idx + 1) % 5 == 0 or (idx + 1) == len(df):
        print(f"Обработано {idx + 1}/{len(df)}")

print(f"\n✅ Готово!")
print(f"Координат получено: {df['Latitude'].notna().sum()} из {len(df)}")

# Сохраняем
t_now = datetime.now().strftime("%Y-%m-%d_%H-%M")
final_path = f"data/2026/processed/cian_final_coords_{len(df)}_{t_now}"

df.to_csv(f"{final_path}.csv", index=False, encoding="utf-8-sig")
df.to_pickle(f"{final_path}.pkl")

print(f"Файл сохранён: {final_path}.csv")

# Показываем результат
display(df[["Address", "Price", "Area", "Rooms", "Floor", "HousingType", "Latitude", "Longitude"]].head(20))

In [ ]:
import pandas as pd
from datetime import datetime

# Если df ещё не загружен — раскомментируй строку ниже
# df = pd.read_csv("data/2026/processed/cian_final_coords_26_2026-03-30_17-14.csv")

# Приводим данные точно под твою модель Apartment
final_df = pd.DataFrame({
    "Address":      df["Address"],
    "Rooms":        df["Rooms"].astype(int),
    "Area":         df["Area"].astype(float),
    "Price":        df["Price"].astype(int),           # decimal в C# примет int
    "Description":  df["Description"],
    "Floor":        df["Floor"].astype(int),
    "HousingType":  df["HousingType"],                 # "Новостройка" / "Вторичное"
    "PhotoUrl":     None,
    "Latitude":     df["Latitude"],
    "Longitude":    df["Longitude"],

    # Дополнительные полезные поля (можно заполнить потом)
    "RegionName":   "Челябинск",
    "Source":       "Cian",
    "ParsedAt":     pd.Timestamp.now(),
    "Url":          df.get("Url", None),
})

# Сохраняем в удобном формате
t_now = datetime.now().strftime("%Y-%m-%d_%H-%M")
final_path = f"data/2026/processed/FINAL_FOR_MODEL_{len(final_df)}_{t_now}"

final_df.to_csv(f"{final_path}.csv", index=False, encoding="utf-8-sig")
final_df.to_pickle(f"{final_path}.pkl")

print(f"✅ Готово! Создан файл специально под твою модель Apartment")
print(f"Файл: {final_path}.csv")
print(f"Количество записей: {len(final_df)}")

display(final_df.head(10))

✅ Готово! Создан файл специально под твою модель Apartment
Файл: data/2026/processed/FINAL_FOR_MODEL_26_2026-03-30_17-14.csv
Количество записей: 26

,Address,Rooms,Area,Price,Description,Floor,HousingType,PhotoUrl,Latitude,Longitude,RegionName,Source,ParsedAt,Url
0,Челябинск,1,56.57,16260000,"1-комн. квартира, 56,57 м², 2/7 этаж",2,Вторичное,None,55.126278,61.379608,Челябинск,Cian,2026-03-30 17:14:55.183499,None
1,улица Харлова,3,68.00,58900008,"3-комн. квартира, 68 м², 10/10 этаж",10,Вторичное,None,55.14964,61.428563,Челябинск,Cian,2026-03-30 17:14:55.183499,None
2,улица 50-летия ВЛКСМ,1,35.00,27000007,"1-комн. квартира, 35 м², 9/9 этаж",9,Вторичное,None,55.240665,61.382689,Челябинск,Cian,2026-03-30 17:14:55.183499,None
3,Челябинск,2,53.10,83692001,"2-комн. квартира, 53,1 м², 3/10 этаж",3,Вторичное,None,55.141065,61.417078,Челябинск,Cian,2026-03-30 17:14:55.183499,None
4,улица Гражданская,3,61.50,49000007,"3-комн. квартира, 61,5 м², 5/9 этаж",5,Вторичное,None,55.140361,61.423902,Челябинск,Cian,2026-03-30 17:14:55.183499,None
5,улица Красного Урала,1,31.20,32000001,"1-комн. квартира, 31,2 м², 1/5 этаж",1,Вторичное,None,55.191786,61.354519,Челябинск,Cian,2026-03-30 17:14:55.183499,None
6,улица Островского,2,45.30,37500008,"2-комн. квартира, 45,3 м², 4/5 этаж",4,Вторичное,None,55.188285,61.369481,Челябинск,Cian,2026-03-30 17:14:55.183499,None
7,улица Петра Сумина,0,24.00,32000001,"Студия, 24 м², 7/11 этаж",7,Вторичное,None,55.174797,61.261181,Челябинск,Cian,2026-03-30 17:14:55.183499,None
8,Челябинск,1,30.70,45854101,"1-комн. квартира, 30,7 м², 5/10 этаж",5,Вторичное,None,55.126278,61.379608,Челябинск,Cian,2026-03-30 17:14:55.183499,None
9,улица Молодогвардейцев,1,17.70,29205001,"1-комн. квартира, 17,7 м², 5/10 этаж",5,Вторичное,None,55.208085,61.317705,Челябинск,Cian,2026-03-30 17:14:55.183499,None